import './globals.css';
import { Inter, Roboto_Mono } from 'next/font/google';
import Navigation from '@/components/Navigation/Navigation';
import cn from 'classnames';

const inter = Inter({ subsets: ['latin'] });
const robotoMono = Roboto_Mono({ subsets: ['latin'] });

export const metadata = {
  title: 'Evervault Starter Kit',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={cn(inter.className, robotoMono.className)}>
        <Navigation />
        <div className='rootLayout'>{children}</div>
      </body>
    </html>
  );
}
